import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Scanner;

/* @author Mark Guerin
 * This program computes charge time, costs, and revenue for a Tesla supercharging station.
 */

public class SuperCharger {

	public static void main(String[] args) {
		
		// Initialize variables
		Scanner keyboard = new Scanner(System.in);
		int stalls = 0;
		int vehicles = 0;
		double cap = 0;
		double percent = 0;
		double chargeTime = 0;
		double chargeCost = 0;
		double stallTotal = 0;
		double stallTime = 0;
		double total = 0;
		double time = 0;
		double totalComplimentary = 0;
		double timeComplimentary = 0;
		int complimentary = 0;
		NumberFormat twoDec = new DecimalFormat("#0.00");
		NumberFormat noDec = new DecimalFormat("#");
		
		// Create a loop for the number of stalls
		
		System.out.println("How many stalls are at the charging station?");
		stalls = keyboard.nextInt();
		
		for (int i = 1; i < stalls+1; i++) {
			
			// Create a loop for the number of vehicles
			
			System.out.println("How many vehicles used stall " + i + "?");
			vehicles = keyboard.nextInt();
			
			for (int j = 1; j < vehicles+1; j++) {
				
				// Calculate and output the charge time and cost of the individual vehicles
				
				System.out.println("Enter the battery capacity of vehicle " + j + " in kWh.");
				cap = keyboard.nextDouble();
						
				System.out.println("What percentage of vehicle " + j + "'s battery was charged?");
				percent = keyboard.nextDouble();
				
				System.out.println("Was vehicle " + j + " a model granted complimentary charging? Enter 1 for yes, or 0 for no.");
				complimentary = keyboard.nextInt();
				System.out.println();
				
				// Add to totals based on whether the vehicle charges for free
				
				if (complimentary == 1) {
					
					// The supercharger charges at a rate of 60 kW on average and costs $0.28 per kWh
					
					chargeTime = ((cap * (percent/100)) / (60));
					chargeCost = (((cap * (percent/100)) * 0.28));
					stallTime += chargeTime;
					totalComplimentary += chargeCost;
					timeComplimentary += chargeTime;
					time += chargeTime;
					
					System.out.println("The owner of vehicle " + j + " was not charged.");
					System.out.println("It took " + noDec.format(Math.floor(chargeTime)) + " hours and " + noDec.format(Math.floor(((chargeTime - Math.floor(chargeTime)) * 60))) + " minutes to charge vehicle " + j + ".");
					System.out.println();
				}
				else {
					chargeTime = ((cap * (percent/100)) / (60));
					chargeCost = (((cap * (percent/100)) * 0.28));
					stallTotal += chargeCost;
					stallTime += chargeTime;
					total += chargeCost;
					time += chargeTime;
					
		// Output values to the user
					
					System.out.println("The owner of this vehicle was charged $" + twoDec.format(chargeCost) + ".");
					System.out.println("It took " + noDec.format(Math.floor(chargeTime)) + " hours and " + noDec.format(Math.floor(((chargeTime - Math.floor(chargeTime)) * 60))) + " minutes to charge this vehicle.");
					System.out.println();
				}
			}
			System.out.println("The total revenue generated by stall " + i + " was $" + twoDec.format(stallTotal) + ".");
			System.out.println("The total time spent charging at stall " + i + " was " + noDec.format(Math.floor(stallTime)) + " hours and " + noDec.format(Math.floor(((stallTime - Math.floor(stallTime)) * 60))) + " minutes.");
			stallTotal = 0;
			stallTime = 0;
			System.out.println();
		}
		System.out.println("The total revenue generated at the charging station was $" + twoDec.format(total) + ".");
		System.out.println("The total time spent charging at the charging station was " + noDec.format(Math.floor(time)) + " hours and " + noDec.format(Math.floor(((time - Math.floor(time)) * 60))) + " minutes.");
		System.out.println("The total cost of free charging given out at the charging station was $" + twoDec.format(totalComplimentary) + ".");
		System.out.println("The total time spent charging for free at the charging station was " + noDec.format(Math.floor(timeComplimentary)) + " hours and " + noDec.format(Math.floor(((timeComplimentary - Math.floor(timeComplimentary)) * 60))) + " minutes.");
		keyboard.close();
	}

}
