import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Scanner;
import java.util.ArrayList;

/* @author Mark Guerin
 * This program computes charge time, costs, and revenue for a Tesla supercharging station.
 */

public class SuperChargerV2 {
	
	public static void main(String[] args) {
		
		// Create objects
		totals total = new totals();
		calculations calculator = new calculations();
		totals.stallTotalList = new ArrayList<Double>();
		totals.stallTimeList = new ArrayList<Double>();
		totals.totalList = new ArrayList<Double>();
		totals.timeList = new ArrayList<Double>();
		totals.totalComplimentaryList = new ArrayList<Double>();
		totals.timeComplimentaryList = new ArrayList<Double>();
		
		// Initialize variables
		Scanner keyboard = new Scanner(System.in);
		int stalls = 0;
		int vehicles = 0;
		double stallSum = 0;
		double stallTimeSum = 0;
		double sum = 0;
		double timeSum = 0;
		NumberFormat twoDec = new DecimalFormat("#0.00");
		NumberFormat noDec = new DecimalFormat("#");
		
		// Create a loop for the number of stalls
		
		System.out.println("How many stalls are at the charging station?");
		stalls = keyboard.nextInt();
		
		for (int i = 1; i < stalls+1; i++) {
			
			// Create a loop for the number of vehicles
			
			System.out.println("How many vehicles used stall " + i + "?");
			vehicles = keyboard.nextInt();
			
			for (int j = 1; j < vehicles+1; j++) {
				
				// Calculate and output the charge time and cost of the individual vehicles
				
				System.out.println("Enter the battery capacity of vehicle " + j + " in kWh.");
				calculator.setCap(keyboard.nextDouble());
						
				System.out.println("What percentage of vehicle " + j + "'s battery was charged?");
				calculator.setPercent(keyboard.nextDouble());
				
				System.out.println("Was vehicle " + j + " a model granted complimentary charging? Enter 1 for yes, or 0 for no.");
				calculator.setComplimentary(keyboard.nextInt());
				System.out.println();
				
				// Add to totals based on whether the vehicle charges for free
				
				calculator.calculateTotals();
			}
		// Output values to the user
			
			
			for(int j = 1; j - 1 < total.stallTotalList.size(); j++) {
				System.out.println("The toll collected for vehicle " + j + " was $" + twoDec.format(total.stallTotalList.get(j - 1)) + ".");
			}
			for(int j = 1; j - 1 < total.stallTimeList.size(); j++) {
				System.out.println("The time spent charging by vehicle " + j + " was " + noDec.format(Math.floor(total.stallTimeList.get(j - 1))) + " hours and " + noDec.format(Math.floor(((total.stallTimeList.get(j - 1) - Math.floor(total.stallTimeList.get(j - 1))) * 60))) + " minutes.");
			}
			System.out.println();
			stallSum = 0;
			stallTimeSum = 0;
			for(int j = 0; j < total.stallTotalList.size(); j++) {
				stallSum += total.stallTotalList.get(j);
			}
			for(int j = 0; j < total.stallTimeList.size(); j++) {
				stallTimeSum += total.stallTimeList.get(j);
			}
			
			System.out.println("The total revenue generated by stall " + i + " was $" + twoDec.format(stallSum) + ".");
			System.out.println("The total time spent charging at stall " + i + " was " + noDec.format(Math.floor(stallTimeSum)) + " hours and " + noDec.format(Math.floor(((stallTimeSum - Math.floor(stallTimeSum)) * 60))) + " minutes.");
			total.clearStallTotalList();
			total.clearStallTimeList();
			System.out.println();
		}
		System.out.println("The total revenue generated at the charging station was $" + twoDec.format(total.getTotal()) + ".");
		System.out.println("The total time spent charging at the charging station was " + noDec.format(Math.floor(total.getTime())) + " hours and " + noDec.format(Math.floor(((total.getTime() - Math.floor(total.getTime())) * 60))) + " minutes.");
		System.out.println("The total cost of free charging given out at the charging station was $" + twoDec.format(total.getTotalComplimentary()) + ".");
		System.out.println("The total time spent charging for free at the charging station was " + noDec.format(Math.floor(total.getTimeComplimentary())) + " hours and " + noDec.format(Math.floor(((total.getTimeComplimentary() - Math.floor(total.getTimeComplimentary())) * 60))) + " minutes.");
		keyboard.close();
	}
}
